package main

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/OpsMx/go-app-base/version"
	"github.com/opsmx/ai-guardian-api/pkg/client"
	"github.com/opsmx/ai-guardian-api/pkg/config"
	"github.com/opsmx/ai-guardian-api/pkg/database"
	"github.com/opsmx/ai-guardian-api/pkg/handlers"
	"github.com/opsmx/ai-guardian-api/pkg/service"
	"github.com/opsmx/ai-guardian-api/pkg/telemetry"
	"github.com/rs/zerolog/log"

	// Swagger imports
	_ "github.com/opsmx/ai-guardian-api/docs" // This will be generated by swag init
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title AI Guardian API
// @version 1.0
// @description AI Guardian API Service
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// parseFlags will create and parse the CLI flags
// and return the path to be used elsewhere
func parseFlags() (string, error) {
	// string that contains the configured configuration path
	var configPath string

	// set up a CLI flag called "-config" to allow users
	// to supply the configuration file
	flag.StringVar(&configPath, "config", "config.yaml", "path to config file")

	// actually parse the flags
	flag.Parse()

	// return the configuration path
	return configPath, nil
}

func main() {
	cfgPath, err := parseFlags()
	if err != nil {
		log.Fatal().Err(err).Msg("failed to parse config file path")
	}

	err = config.ParseConfig(cfgPath)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to parse config")
	}

	if err := config.LoadWorkflowTemplate("schema/gh-actions/aiguardian-remediation.yml"); err != nil {
		log.Fatal().Err(err).Msg("failed to load workflow template")
	}

	log.Info().Msg(version.VersionString())
	if config.GetShowVersion() {
		os.Exit(0)
	}

	// Create main context for the application
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Initialize OpenTelemetry with Prometheus
	enabled, serviceName, serviceVersion, _, _ := config.GetTelemetryConfig()

	telemetryProvider, err := telemetry.Initialize(telemetry.Config{
		Enabled:        enabled,
		ServiceName:    serviceName,
		ServiceVersion: serviceVersion,
	})
	if err != nil {
		log.Fatal().Err(err).Msg("Failed to initialize telemetry")
	}
	defer func() {
		shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer shutdownCancel()
		if err := telemetryProvider.Shutdown(shutdownCtx); err != nil {
			log.Error().Err(err).Msg("Error shutting down telemetry")
		}
	}()

	// Start session manager
	if err := config.StartSessionManager(ctx); err != nil {
		log.Fatal().Err(err).Msg("Failed to start session manager")
	}
	defer config.StopSessionManager() // Ensure session manager is stopped on exit

	// Initialize database connections
	pgConnStr := config.GetPgConfig()
	rdUser, rdPassword, rdAddress := config.GetRedisConfig()

	err = database.InitDatabase(pgConnStr, rdUser, rdPassword, rdAddress)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to initialize database")
	}
	defer func() {
		if err := database.Close(); err != nil {
			log.Error().Err(err).Msg("error closing database connections")
		}
	}()

	// Get session Store, default to in-mem
	err = config.AuthenticatorSessionStore()
	if err != nil {
		log.Fatal().Err(err).Msg("error configuring Session store")
	}

	// Initialize and start polling service if enabled
	// This service handles both:
	// 1. Polling scans table for pending/running scans
	// 2. Polling projects table for auto-scan enabled projects
	var pollingService *service.PollingService
	if config.GetPollingEnabled() {
		// Create SSD client for polling service
		ssdClient := client.NewSSDClient()

		pollingInterval := time.Duration(config.GetPollingIntervalSeconds()) * time.Second
		pollingService = service.NewPollingService(ssdClient, pollingInterval)

		// Start polling service in background
		go pollingService.Start(ctx)
	} else {
		log.Info().Msg("Polling service is disabled")
	}

	// Setup routes
	router := handlers.SetupRoutes()

	// Add Swagger route
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	// Setup middleware
	middleware := handlers.SetupMiddleware()
	handler := handlers.ApplyMiddleware(router, middleware...)

	// Start server
	addr := fmt.Sprintf(":%s", config.GetApiPort())
	log.Info().Msgf("Server starting on %s", addr)
	// Setup graceful shutdown
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		<-sigChan
		log.Info().Msg("Shutdown signal received, stopping services...")

		// Stop polling service if running
		if pollingService != nil {
			pollingService.Stop()
			log.Info().Msg("Polling service stopped")
		}

		// Stop session manager
		config.StopSessionManager()

		// Close database connections
		if err := database.Close(); err != nil {
			log.Error().Err(err).Msg("error closing database connections")
		}

		// Cancel context to stop all background goroutines
		cancel()

		log.Info().Msg("Graceful shutdown completed")
		os.Exit(0)
	}()

	if err := http.ListenAndServe(addr, handler); err != nil {
		log.Fatal().Err(err).Msg("Failed to start server")
	}
}
